name: Robot Test

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  test:
    runs-on: ubuntu-latest
    # container: ghcr.io/joseajunior/basecontainer:latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Updating Pip
        run: |
          python -m pip install --upgrade pip

      - name: Installing requirements
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Show installed packages
        run: |
          pip freeze

      - name: Run Tests Using Robot For Android
        if: always()
        run: |
            robot --variable version:12 --variable platformName:Android --variable deviceName:"Galaxy S22 5G" --variable isRealMobile:true --variable visual:false --variable network:false --variable console:false --report None --output reports/DriverDash/Android/DriveDash_samsung_output.xml --log reports/DriverDash/Android/DriverDash_samsung_log.html --exclude db DriverDash/tests/Android/DriverDash.robot

      - name: Run Tests Using Robot For iOS
        if: always()
        run: |
            robot --variable version:16 --variable platformName:iOS --variable deviceName:"iPhone 13" --variable isRealMobile:true --variable visual:false --variable network:false --variable console:false --report None --output reports/DriverDash/iOS/DriveDash_iphone_13_output.xml --log reports/DriverDash/iOS/DriverDash_iphone_13_log.html --exclude db DriverDash/tests/iOS/DriverDash.robot

      - name: Create test results file
        run: |
          rebot --name Frontend --nostatusrc --outputdir logs --output ${{ github.workspace }}/reports/output.xml ${{ github.workspace }}/reports/DriverDash/Android/DriveDash_samsung_output.xml ${{ github.workspace }}/reports/DriverDash/iOS/DriveDash_iphone_13_output.xml

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports

  generate_report:
    if: always()
    needs: [test] 
    runs-on: ubuntu-latest
    steps:
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Get Repository Owner & Name
          run: |
            export OWNER="$(echo "${{ github.repository }}" | awk -F / '{print $1}' | sed -e "s/:refs//")"
            export REPO="$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
            echo "REPOSITORY_OWNER=$OWNER" >> "$GITHUB_ENV"
            echo "REPOSITORY_NAME=$REPO" >> "$GITHUB_ENV"

        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v0.1
          env:
            GH_ACCESS_TOKEN: ${{ secrets.TOKEN }}
            REPO_OWNER: ${{ env.REPOSITORY_OWNER }}
            COMMIT_SHA: ${{ github.sha }}
            REPOSITORY: ${{ env.REPOSITORY_NAME }}
            REPORT_PATH: reports