name: Robocop Linter

on:
  push:
    branches: [ robocop ]

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  linter:
    name: Linter
    runs-on: ubuntu-latest
    # continue even if Robocop returns issues and fails step
    continue-on-error: true
    permissions:
      # required for issues to be recorded
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework-robocop
      - name: Run robocop
        continue-on-error: true
        run: python -m robocop --reports sarif .
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: .sarif.json
          category: robocop
